runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  secure: always

env_variables:
  FUNCTIONS_URI: 'https://us-central1-future-app-backend.cloudfunctions.net/webhookcde99ee3b82d44c18d6bfd8d017f8232'
